repos:
- repo: https://github.com/awslabs/git-secrets
  rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38 # Must be post the 1.3.0 release
  hooks:
  - id: git-secrets
    entry: git-secrets --scan
    files: .
    args: [--untracked]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    #- id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

# Check shell scripts example
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
    - id: shellcheck
      exclude: import.sh

- repo: https://github.com/dnephin/pre-commit-golang
  rev: 74f6978a867aa40e8af6b810ba0f5342c51adc0c
  hooks:
    - id: go-fmt
    # This complains due to the doc generation. Will investigate later.
    #- id: go-vet
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    # The code needs a little updating before we can enable these.
    #- id: golangci-lint
    #- id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
